# Generated by Django 2.1 on 2018-08-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
