# Generated by Django 2.1 on 2018-08-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0003_auto_20180805_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
