# Generated by Django 2.1 on 2018-09-04 21:45

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0003_auto_20180826_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='useragent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='useragent',
            field=models.TextField(blank=True),
        ),
    ]
