# Generated by Django 2.1.5 on 2019-01-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0005_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='reported',
        ),
    ]
